name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Generate coverage report
        run: |
          coverage run --parallel-mode -m unittest
          coverage combine
          coverage xml -i
        env:
          COVERAGE_RUN: True
      - name: Upload report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
