name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy coverage
      - name: Build dist and test with unittest on Windows
        run: |
          python -m unittest
      - name: Generate coverage report
        run: |
          coverage run --parallel-mode -m unittest
          coverage combine
          coverage xml -i
        env:
          COVERAGE_RUN: True
      - name: Upload report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
